# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Step 2. Import the dataset [wind.csv](https://github.com/guipsamora/pandas_exercises/blob/master/Stats/Wind_Stats/wind.data) from the folder

In [36]:
pd.read_csv("C:/Data Sets/Data Sets/wind.data")

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,78,12,27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,78,12,28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,78,12,29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,78,12,30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,78,12,31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [37]:
data = pd.read_csv("C:/Data Sets/Data Sets/wind.data")

#data.dtypes
#Yr, Mo, Dy are int64

#d2 = data.loc[:,['Yr','Mo','Dy']]

#data.loc[:, data.dtypes=='int64'].applymap(lambda x: pd.to_datetime(x,format = '%Y'))
#pd.to_datetime(d2, format = '%d/%m/%Y')
#data.loc[:, ['Yr','Mo','Dy']]

data['date']=data['Yr'].astype('str')+data['Mo'].astype('str')+data['Dy'].astype('str')
data.drop(columns=['Yr','Mo','Dy'], inplace = True)
data['date']= pd.to_datetime(data.date, format = '%y%m%d')
data

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date
0,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,2061-01-01
1,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,2061-01-02
2,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,2061-01-03
3,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,2061-01-04
4,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,2061-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08,1978-12-27
6570,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46,1978-12-28
6571,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58,1978-12-29
6572,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79,1978-12-30
6573,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08,1978-12-31

### Step 4. Year 2061 is seemingly imporoper. Convert every year which are < 70 to 19XX instead of 20XX.

In [38]:
np.where(data.date.dt.year>2020, data.date+pd.DateOffset(years=-100), data.date)

array(['1961-01-01T00:00:00.000000000', '1961-01-02T00:00:00.000000000',
       '1961-01-03T00:00:00.000000000', ...,
       '1978-12-29T00:00:00.000000000', '1978-12-30T00:00:00.000000000',
       '1978-12-31T00:00:00.000000000'], dtype='datetime64[ns]')

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [40]:
data['date'] = np.where(data.date.dt.year>2020, data.date+pd.DateOffset(years=-100), data.date)
data.set_index('date', inplace = True)

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [45]:
data.isna().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [46]:
data.notna().sum()

#data.count() wll also work.

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [48]:
data.mean().mean()

10.227982360836924

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [59]:
loc_stats = data.describe().T
loc_stats.loc[:,['min','max','mean','std']]

      min    max       mean       std
RPT  0.67  35.80  12.362987  5.618413
VAL  0.21  33.37  10.644314  5.267356
ROS  1.50  33.84  11.660526  5.008450
KIL  0.00  28.46   6.306468  3.605811
SHA  0.13  37.54  10.455834  4.936125
BIR  0.00  26.16   7.092254  3.968683
DUB  0.00  30.37   9.797343  4.977555
CLA  0.00  31.08   8.495053  4.499449
MUL  0.00  25.88   8.493590  4.166872
CLO  0.04  28.21   8.707332  4.503954
BEL  0.13  42.38  13.121007  5.835037
MAL  0.67  42.54  15.599079  6.699794

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [76]:
day_stats = data.T.describe().T
day_stats.loc[:,['min','max','mean','std']]

             min    max       mean       std
date
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356
...          ...    ...        ...       ...
1978-12-27  8.08  40.08  16.708333  7.868076
1978-12-28  5.00  41.46  15.150000  9.687857
1978-12-29  8.71  29.58  14.890000  5.756836
1978-12-30  9.13  28.79  15.367500  5.540437
1978-12-31  9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [81]:
data[data.index.month ==1].mean()

RPT    14.407735
VAL    12.362146
ROS    13.290470
KIL     6.926239
SHA    11.205064
BIR     7.827393
DUB    11.953120
CLA     9.377511
MUL     9.469915
CLO     9.880812
BEL    14.582350
MAL    18.332051
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [99]:
#data.groupby(data.index.year).count()

data.pivot_table(index = data.index.year , aggfunc = 'count', dropna = True)

      BEL  BIR  CLA  CLO  DUB  KIL  MAL  MUL  ROS  RPT  SHA  VAL
date
1961  365  365  363  364  362  361  362  362  363  360  363  362
1962  365  365  365  365  365  364  364  365  365  364  365  365
1963  365  365  365  365  365  365  365  365  365  365  365  365
1964  366  366  366  366  366  366  366  366  366  366  366  366
1965  365  365  365  365  365  365  365  365  365  365  365  365
1966  365  365  365  365  365  365  365  365  365  365  365  365
1967  365  365  365  365  365  365  365  365  365  365  365  365
1968  366  366  366  366  366  366  366  366  366  366  366  366
1969  365  365  365  365  365  365  365  365  365  365  365  365
1970  365  365  365  365  365  365  365  365  365  365  365  365
1971  365  365  365  365  365  365  365  365  365  365  365  365
1972  366  366  366  366  366  366  366  366  366  366  366  366
1973  365  365  365  365  365  365  365  365  365  365  365  365
1974  365  365  365  365  365  365  365  365  365  365  365  365
1975  365  365  365  365  365  365  365  365  365  365  365  365
1976  366  366  366  366  366  366  366  366  366  366  366  366
1977  365  365  365  365  365  365  365  365  365  365  365  365
1978  365  365  365  365  365  365  365  365  365  365  365  365

### Step 13. Downsample the record to a monthly frequency for each location.

In [102]:
#data.groupby(data.index.month).count()
data.pivot_table(index = data.index.month , aggfunc = 'count', dropna = True)

      BEL  BIR  CLA  CLO  DUB  KIL  MAL  MUL  ROS  RPT  SHA  VAL
date
1     234  234  233  234  234  234  234  234  234  234  233  233
2     508  508  508  508  508  506  508  508  507  508  508  508
3     558  558  558  558  558  557  556  556  558  556  558  558
4     540  540  540  540  540  540  540  540  540  540  540  540
5     558  558  558  558  557  557  558  558  558  558  558  557
6     540  540  540  540  540  540  539  540  540  539  540  540
7     558  558  558  558  557  558  558  558  558  558  558  558
8     558  558  558  557  558  558  557  558  558  557  558  558
9     540  540  539  540  540  539  540  540  539  540  540  539
10    558  558  558  558  558  558  558  557  558  557  558  558
11    702  702  702  702  701  702  702  702  702  702  701  702
12    720  720  720  720  720  720  720  720  720  719  720  720

### Step 14. Downsample the record to a weekly frequency for each location.

In [104]:
#data.groupby(data.index.week).count()
data.pivot_table(index = data.index.week , aggfunc = 'count', dropna = True)

      BEL  BIR  CLA  CLO  DUB  KIL  MAL  MUL  ROS  RPT  SHA  VAL
date
1     126  126  125  126  126  126  126  126  126  126  126  125
2      53   53   53   53   53   53   53   53   53   53   53   53
3      13   13   13   13   13   13   13   13   13   13   13   13
4      12   12   12   12   12   12   12   12   12   12   12   12
5     102  102  102  102  102  102  102  102  102  102  102  102
6     126  126  126  126  126  126  126  126  126  126  126  126
7     126  126  126  126  126  125  126  126  126  126  126  126
8     126  126  126  126  126  125  126  126  126  126  126  126
9     126  126  126  126  126  126  125  125  125  125  126  126
10    126  126  126  126  126  126  126  126  126  125  126  126
11    126  126  126  126  126  126  125  126  126  126  126  126
12    126  126  126  126  126  126  126  126  126  126  126  126
13    126  126  126  126  126  125  126  125  126  126  126  126
14    126  126  126  126  126  126  126  126  126  126  126  126
15    126  126  126  126  126  126  126  126  126  126  126  126
16    126  126  126  126  126  126  126  126  126  126  126  126
17    126  126  126  126  126  126  126  126  126  126  126  126
18    126  126  126  126  126  126  126  126  126  126  126  126
19    126  126  126  126  125  126  126  126  126  126  126  126
20    126  126  126  126  126  126  126  126  126  126  126  125
21    126  126  126  126  126  125  126  126  126  126  126  126
22    126  126  126  126  126  126  126  126  126  126  126  126
23    126  126  126  126  126  126  126  126  126  126  126  126
24    126  126  126  126  126  126  126  126  126  126  126  126
25    126  126  126  126  126  126  126  126  126  126  126  126
26    126  126  126  126  126  126  125  126  126  125  126  126
27    126  126  126  126  125  126  126  126  126  126  126  126
28    126  126  126  126  126  126  126  126  126  126  126  126
29    126  126  126  126  126  126  126  126  126  126  126  126
30    126  126  126  126  126  126  126  126  126  126  126  126
31    126  126  126  126  126  126  126  126  126  126  126  126
32    126  126  126  125  126  126  126  126  126  125  126  126
33    126  126  126  126  126  126  125  126  126  126  126  126
34    126  126  126  126  126  126  126  126  126  126  126  126
35    126  126  126  126  126  126  126  126  126  126  126  126
36    126  126  126  126  126  126  126  126  126  126  126  126
37    126  126  126  126  126  126  126  126  126  126  126  126
38    126  126  125  126  126  125  126  126  125  126  126  126
39    126  126  126  126  126  126  126  126  126  126  126  125
40    126  126  126  126  126  126  126  126  126  126  126  126
41    126  126  126  126  126  126  126  126  126  125  126  126
42    126  126  126  126  126  126  126  126  126  126  126  126
43    126  126  126  126  126  126  126  125  126  126  126  126
44    195  195  195  195  195  195  195  195  195  195  195  195
45    215  215  215  215  215  215  215  215  215  215  214  215
46    130  130  130  130  130  130  130  130  130  130  130  130
47    126  126  126  126  125  126  126  126  126  126  126  126
48    163  163  163  163  163  163  163  163  163  163  163  163
49    234  234  234  234  234  234  234  234  234  233  234  234
50    143  143  143  143  143  143  143  143  143  143  143  143
51    126  126  126  126  126  126  126  126  126  126  126  126
52    127  127  127  127  127  127  127  127  127  127  126  127
53     21   21   21   21   21   21   21   21   21   21   21   21

### Step 15. Calculate the mean windspeed for each month in the dataset.  
#### Treat January 1961 and January 1962 as *different* months.
#### (hint: first find a  way to create an identifier unique for each month.)

In [106]:
data.groupby(data.index.to_period('m')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
1961-01,13.983846,12.385833,11.666923,6.826923,10.151667,7.179231,11.008462,7.600833,8.442308,8.879231,12.714615,13.451538
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,15.193846,13.518462,13.178974,6.747949,10.729487,7.887692,10.917692,8.927179,9.707949,9.619231,15.976667,19.875641
1978-12,16.742250,13.925500,15.323250,7.552750,12.120750,9.282250,12.662000,10.760000,10.956000,11.218000,14.545500,22.146000

### Step 16. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [115]:
#data.groupby(data.index.week).agg([np.min,np.max,np.mean,np.std]).iloc[0:52]

data.pivot_table(index = data.index.week, aggfunc = [np.min,np.max,np.mean,np.std]).iloc[0:52]

      amin                                                         ...  \
       BEL   BIR   CLA   CLO   DUB   KIL    MAL   MUL   ROS   RPT  ...
date                                                               ...
1     0.58  0.13  0.00  0.58  2.62  0.37   4.17  0.54  3.79  2.62  ...
2     1.71  1.42  0.37  0.33  2.54  0.63   3.63  2.25  3.54  5.29  ...
3     6.50  2.29  4.29  2.58  3.17  1.21   6.79  1.00  6.38  7.54  ...
4     7.50  1.29  2.75  2.79  6.92  2.21  12.29  4.42  4.54  2.08  ...
5     2.04  0.00  0.21  0.50  1.92  0.37   4.83  0.83  3.21  2.71  ...
6     2.04  0.13  0.46  0.67  1.75  0.33   5.29  0.50  3.67  2.79  ...
7     2.67  0.00  0.17  0.83  2.79  0.42   5.09  0.83  3.50  2.92  ...
8     2.17  0.04  0.25  0.75  1.46  0.67   3.04  0.96  2.37  1.54  ...
9     2.13  0.21  0.96  1.75  1.08  0.58   3.17  1.17  2.50  0.67  ...
10    2.21  0.00  1.08  0.25  1.08  0.50   2.46  0.54  3.42  2.29  ...
11    2.25  0.33  0.67  0.71  2.29  0.87   4.54  1.71  2.92  1.46  ...
12    2.96  0.13  1.83  0.37  3.50  0.67   3.21  1.25  3.17  2.92  ...
13    2.50  0.25  0.96  1.67  2.04  1.08   2.04  1.17  2.71  2.79  ...
14    2.88  0.29  1.25  1.50  1.42  1.63   3.71  1.17  3.04  3.88  ...
15    4.46  0.79  1.25  1.38  2.13  1.25   4.33  1.46  1.75  4.42  ...
16    3.21  0.21  1.46  1.38  1.33  0.63   4.17  1.38  3.33  3.67  ...
17    3.75  0.17  1.38  0.50  1.21  0.83   2.21  1.54  2.54  3.46  ...
18    3.29  0.29  0.54  1.29  0.92  0.46   2.58  0.67  3.58  1.63  ...
19    4.71  0.13  1.38  1.83  1.63  1.04   3.33  1.13  2.29  3.54  ...
20    4.12  0.54  1.67  1.42  1.21  0.92   3.58  1.38  3.46  2.42  ...
21    3.21  0.04  1.29  0.96  0.83  1.08   4.04  1.00  3.04  2.62  ...
22    2.67  0.83  1.42  0.92  0.83  1.38   1.75  0.96  3.50  2.04  ...
23    4.04  0.00  1.33  0.87  0.21  0.71   2.21  0.50  2.75  2.17  ...
24    3.08  0.71  0.75  0.54  1.46  1.21   2.79  1.50  1.87  1.00  ...
25    2.96  1.25  1.00  0.79  1.75  1.25   3.08  1.67  4.21  2.92  ...
26    4.21  0.25  1.00  1.17  1.79  1.92   4.54  1.71  1.83  3.46  ...
27    4.04  0.50  0.21  0.96  1.46  1.29   4.50  1.29  2.83  2.00  ...
28    3.25  0.29  0.37  0.67  0.83  0.75   2.13  0.54  3.42  2.75  ...
29    3.33  0.25  0.67  0.37  1.38  1.17   2.29  0.37  2.92  1.71  ...
30    3.58  0.13  1.13  0.92  1.42  0.96   2.88  0.46  2.50  1.25  ...
31    3.46  0.46  0.46  0.67  1.38  1.63   2.25  1.54  3.08  2.79  ...
32    3.29  0.71  0.71  0.46  0.92  1.42   3.04  0.58  4.21  2.67  ...
33    1.58  0.37  0.63  0.79  0.71  0.83   2.17  0.87  2.92  3.17  ...
34    1.63  0.21  0.08  0.13  0.71  1.21   3.37  1.50  3.54  2.42  ...
35    2.67  0.08  0.71  0.04  0.37  0.83   3.83  0.54  2.42  0.96  ...
36    1.63  0.54  0.54  0.13  1.25  0.87   3.37  0.33  2.29  1.50  ...
37    2.54  0.21  0.42  0.29  1.42  0.58   2.83  0.46  2.96  1.79  ...
38    2.79  0.58  0.29  0.29  0.54  0.46   0.67  0.67  2.37  0.79  ...
39    2.21  1.17  0.42  0.46  0.42  0.87   4.04  1.13  2.25  3.37  ...
40    2.42  0.33  0.13  1.08  0.42  0.92   2.04  0.92  2.54  2.37  ...
41    2.54  0.04  0.25  0.21  1.08  0.33   3.33  0.29  2.37  3.04  ...
42    3.37  0.29  0.42  1.04  1.04  0.25   5.04  0.50  1.96  2.04  ...
43    2.96  0.37  0.63  1.58  1.13  0.29   6.17  1.58  2.17  1.50  ...
44    2.62  0.46  0.17  1.58  0.92  0.17   4.54  0.42  2.37  2.00  ...
45    1.50  0.08  0.46  0.04  2.79  0.21   2.96  0.37  3.67  1.63  ...
46    0.71  0.17  0.00  0.33  2.17  0.13   2.00  0.58  1.83  2.92  ...
47    1.25  0.00  0.08  1.04  0.00  0.25   4.25  0.17  1.50  2.67  ...
48    1.87  0.04  0.00  0.04  0.46  0.08   4.79  0.00  3.00  3.08  ...
49    0.13  0.17  0.04  0.46  0.54  0.33   3.25  0.29  2.75  0.67  ...
50    2.29  0.00  0.04  0.13  1.21  0.00   6.50  0.37  2.83  1.96  ...
51    2.88  0.04  0.54  0.92  1.21  0.33   2.62  0.71  3.92  1.79  ...
52    0.67  0.46  0.33  0.79  1.96  0.42   4.58  1.83  2.13  3.00  ...

           std                                                              \
           CLA       CLO       DUB       KIL       MAL       MUL       ROS
date
1     5.572594  5.290276  5.062046  4.687681  7.047385  4.641781  5.589253
2     4.750676  4.675396  5.222919  3.765926  6.881317  4.221825  5.725268
3     4.405327  4.533910  5.285621  3.742669  6.579779  4.504979  5.573924
4     5.544580  5.546597  5.232638  3.900491  8.356038  5.332304  6.433663
5     5.105745  4.793620  5.072074  3.816580  6.482263  4.360901  5.120175
6     4.565358  4.624377  4.961367  3.764455  6.092634  4.627897  4.923072
7     5.385052  5.241451  5.471027  4.145513  6.819665  4.769665  5.015288
8     4.955935  5.096524  5.629268  4.135992  7.251216  4.655384  6.000005
9     4.695696  4.548139  5.030806  3.611449  6.191920  3.891743  4.734627
10    4.706714  4.978696  5.472030  4.296609  6.572057  4.459569  6.115155
11    5.352835  5.112287  5.385487  4.146945  7.428510  4.738673  5.654429
12    4.613769  4.517893  5.248829  3.881174  6.902719  4.547905  5.322566
13    4.487024  4.379889  4.933781  3.235555  6.644671  4.486575  4.806939
14    4.188499  4.384778  5.179663  3.503805  6.979889  4.177817  5.490509
15    4.593282  4.272218  5.047086  3.513320  6.795427  4.202997  4.781080
16    4.139256  4.220644  4.574593  3.561543  5.328738  3.766336  5.032650
17    3.896546  4.217093  4.574245  3.254163  6.018248  3.729198  4.794157
18    4.174833  4.082519  4.145967  3.045277  6.216011  3.830264  4.085285
19    4.271872  4.348034  4.430291  3.432018  5.699596  3.782671  5.305562
20    4.131662  4.520118  4.893045  3.371625  5.865042  4.167407  4.502200
21    3.836572  3.691034  4.233411  3.055061  5.258812  3.767712  4.943086
22    3.363868  3.354776  3.496048  2.279229  5.001233  3.387331  5.022040
23    3.478149  3.366850  3.686859  2.533931  5.383357  3.108832  5.046720
24    3.664466  3.994689  4.065439  2.725403  5.419266  3.368293  4.881431
25    4.100241  4.260790  4.634523  3.145359  5.873487  3.910905  3.544629
26    3.029853  3.233524  3.547179  2.348039  4.516285  2.893628  3.620651
27    3.423317  3.720332  3.758722  2.686712  5.292558  3.192081  3.314345
28    3.709763  3.662487  3.779491  2.669568  5.565273  3.458463  3.661512
29    3.603905  3.733708  3.943016  2.539948  5.472898  3.259089  3.820782
30    3.611669  3.470866  3.734464  2.358152  5.055287  3.199508  3.767112
31    3.602100  3.502351  3.631415  2.204732  5.053851  2.995495  3.403761
32    3.609097  3.676547  3.488207  2.491611  5.353812  3.291622  3.639591
33    4.070338  4.084187  4.241708  3.110557  5.587084  3.640329  4.186147
34    4.362172  4.206738  4.494953  2.974151  5.642352  3.564286  3.808310
35    4.198024  4.115397  4.142594  2.961108  5.962103  3.655814  4.254049
36    3.677473  3.713513  4.211560  2.903820  5.692819  3.773584  4.378142
37    4.310187  4.671456  4.573940  3.653077  6.350553  4.186744  5.133529
38    3.683295  3.609957  3.782360  2.685250  5.420672  3.180781  4.050428
39    4.693838  4.402953  5.026211  3.406643  6.943457  4.000775  4.386918
40    3.782258  3.747967  4.399508  2.998221  6.364950  3.864336  4.093114
41    4.543378  4.367278  4.616750  3.289071  6.537501  3.921517  4.695276
42    4.178309  4.454747  4.267462  3.807005  6.401907  3.829479  4.990025
43    4.747229  4.621225  5.234638  3.917110  6.799425  4.266622  5.189746
44    4.703067  4.790342  5.588244  4.088830  7.021542  4.556701  5.081396
45    4.654330  4.613376  5.009374  3.988132  7.140148  4.387589  5.430456
46    5.226609  5.302986  5.902938  4.724369  8.585392  5.111269  6.114209
47    4.276420  4.176509  4.906768  3.525402  6.677397  4.118525  4.526871
48    4.961774  4.873247  5.560471  4.379388  6.642826  4.595855  4.861506
49    5.039520  4.745238  5.046590  4.314195  7.020126  4.673697  5.040331
50    5.412547  5.475668  5.359522  4.597394  6.500093  4.815876  5.282827
51    4.768590  4.269109  5.399759  3.784468  6.303056  4.409732  4.901944
52    4.872562  4.510556  4.674302  3.956735  6.834899  4.398782  5.976053


           RPT       SHA       VAL
date
1     6.341312  5.285201  5.976741
2     5.462035  5.213310  5.408451
3     4.875431  3.767389  3.616921
4     6.112314  6.129405  6.898560
5     5.648340  5.087789  6.075989
6     5.620867  4.991844  5.845671
7     5.916627  5.734126  5.974678
8     5.923096  5.317412  5.428889
9     5.240324  5.018766  5.206450
10    6.165086  5.309196  5.842768
11    6.412912  5.410475  5.553335
12    5.509073  5.160086  5.109913
13    5.278774  4.994303  5.126852
14    5.698092  5.039414  5.048327
15    5.335705  4.884393  4.679762
16    5.248461  4.661589  5.032893
17    5.378706  4.672307  4.758561
18    4.367054  4.466483  4.274369
19    5.517038  4.751922  4.345500
20    5.404169  4.920203  4.876184
21    5.200316  4.919717  4.471767
22    4.053188  3.758069  3.521804
23    4.516349  4.021395  3.909693
24    4.410570  3.915909  4.503438
25    4.415008  4.522242  4.116320
26    3.868826  3.565433  3.476639
27    4.742847  4.019936  3.715586
28    4.661313  4.295285  3.932700
29    4.578130  3.713357  3.921746
30    4.056483  3.932700  3.535041
31    4.143365  3.830133  3.691241
32    3.982815  3.953439  4.076909
33    4.914926  4.559596  4.180112
34    4.874965  4.628354  4.372665
35    4.976603  5.169258  4.816354
36    5.086312  4.347830  4.585837
37    5.662910  5.095621  4.902647
38    4.585719  3.992737  4.646788
39    5.313510  4.714666  4.898134
40    4.458238  4.585729  4.799801
41    5.400736  5.113362  5.352465
42    5.718162  4.536547  5.149048
43    6.116732  5.035145  5.455591
44    5.833335  5.426092  5.859151
45    6.254240  4.924809  5.849996
46    6.405892  5.910845  6.124571
47    5.234852  4.436854  5.278304
48    6.125372  5.579658  6.074723
49    6.192947  5.277132  5.657554
50    6.803921  5.653207  6.131647
51    5.313674  5.095079  5.537990
52    5.701056  5.017232  5.488104

[52 rows x 48 columns]